apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foo
  name: test-default
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
